version: '3'
services:
  elasticsearch:
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # mem_limit: 1g
    ports:
      - 9200:9200
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 99
        window: 120s
    networks:
      - erepro


  listings:
    hostname: listings
    container_name: listings
    build: services/listings
    ports:
      - 9090:9090
    expose:
      - 9090
    depends_on:
      - elasticsearch
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 99
        window: 120s
    networks:
      - erepro

  listings-gw:
    hostname: listings-gw
    container_name: listings-gw
    build: services/listings-gw
    ports:
      - 8080:8080
    depends_on:
      - listings
    environment:
      - HOSTPORT=0.0.0.0:8080
      - ENDPOINT=listings:9090
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 99
        window: 120s
    networks:
      - erepro

  branches:
    hostname: branches
    container_name: branches
    build: services/branches
    ports:
      - 9091:9090
    expose:
      - 9090
    depends_on:
      - elasticsearch
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 99
        window: 120s
    networks:
      - erepro

  branches-gw:
    hostname: branches-gw
    container_name: branches-gw
    build: services/branches
    ports:
      - 8081:8080
    depends_on:
      - branches
    environment:
      - HOSTPORT=0.0.0.0:8080
      - ENDPOINT=branches:9090
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 99
        window: 120s
    networks:
      - erepro

networks:
  erepro:
